authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "Support for creating packed tables of strings and save/load simple tables with values"
keywords = ["Strings"]
license = "MIT"
name = "StrTables"
uuid = "9700d1a9-a7c8-5760-9816-a99fda30bb8f"
version = "1.0.1"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
julia = "^1.0.0"
